// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: app/protos/student.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Student_Login_FullMethodName           = "/book.Student/Login"
	Student_TokenValidation_FullMethodName = "/book.Student/TokenValidation"
	Student_SignUp_FullMethodName          = "/book.Student/SignUp"
)

// StudentClient is the client API for Student service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentClient interface {
	Login(ctx context.Context, in *LoginRequestBody, opts ...grpc.CallOption) (*LoginResponseBody, error)
	TokenValidation(ctx context.Context, in *Token, opts ...grpc.CallOption) (*GetTokenResponseBody, error)
	SignUp(ctx context.Context, in *SignUpRequestBody, opts ...grpc.CallOption) (*SignUpResponseBody, error)
}

type studentClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentClient(cc grpc.ClientConnInterface) StudentClient {
	return &studentClient{cc}
}

func (c *studentClient) Login(ctx context.Context, in *LoginRequestBody, opts ...grpc.CallOption) (*LoginResponseBody, error) {
	out := new(LoginResponseBody)
	err := c.cc.Invoke(ctx, Student_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClient) TokenValidation(ctx context.Context, in *Token, opts ...grpc.CallOption) (*GetTokenResponseBody, error) {
	out := new(GetTokenResponseBody)
	err := c.cc.Invoke(ctx, Student_TokenValidation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClient) SignUp(ctx context.Context, in *SignUpRequestBody, opts ...grpc.CallOption) (*SignUpResponseBody, error) {
	out := new(SignUpResponseBody)
	err := c.cc.Invoke(ctx, Student_SignUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServer is the server API for Student service.
// All implementations must embed UnimplementedStudentServer
// for forward compatibility
type StudentServer interface {
	Login(context.Context, *LoginRequestBody) (*LoginResponseBody, error)
	TokenValidation(context.Context, *Token) (*GetTokenResponseBody, error)
	SignUp(context.Context, *SignUpRequestBody) (*SignUpResponseBody, error)
	mustEmbedUnimplementedStudentServer()
}

// UnimplementedStudentServer must be embedded to have forward compatible implementations.
type UnimplementedStudentServer struct {
}

func (UnimplementedStudentServer) Login(context.Context, *LoginRequestBody) (*LoginResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedStudentServer) TokenValidation(context.Context, *Token) (*GetTokenResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenValidation not implemented")
}
func (UnimplementedStudentServer) SignUp(context.Context, *SignUpRequestBody) (*SignUpResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedStudentServer) mustEmbedUnimplementedStudentServer() {}

// UnsafeStudentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentServer will
// result in compilation errors.
type UnsafeStudentServer interface {
	mustEmbedUnimplementedStudentServer()
}

func RegisterStudentServer(s grpc.ServiceRegistrar, srv StudentServer) {
	s.RegisterService(&Student_ServiceDesc, srv)
}

func _Student_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Student_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).Login(ctx, req.(*LoginRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Student_TokenValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).TokenValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Student_TokenValidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).TokenValidation(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _Student_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Student_SignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).SignUp(ctx, req.(*SignUpRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

// Student_ServiceDesc is the grpc.ServiceDesc for Student service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Student_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "book.Student",
	HandlerType: (*StudentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Student_Login_Handler,
		},
		{
			MethodName: "TokenValidation",
			Handler:    _Student_TokenValidation_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _Student_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/protos/student.proto",
}
